Configurable Keybindings
thestinger/termite pull request #617
Opened 2018-07-10 19:24 UTC by ThrosturX

Almost the same as #610 , except doesn't contain the mode indicator stuff.

2018-07-11 18:33 UTC, jelly commented
This is still all dead code:
```
termite.cc: At global scope:
termite.cc:1029:13: warning: ‘void move_forward_end_blank_word(VteTerminal*, select_info*)’ defined but not used [-Wunused-function]
 static void move_forward_end_blank_word(VteTerminal *vte, select_info *select) {
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~
termite.cc:1025:13: warning: ‘void move_forward_end_word(VteTerminal*, select_info*)’ defined but not used [-Wunused-function]
 static void move_forward_end_word(VteTerminal *vte, select_info *select) {
             ^~~~~~~~~~~~~~~~~~~~~
termite.cc:795:13: warning: ‘long int bottom_row(VteTerminal*)’ defined but not used [-Wunused-function]
 static long bottom_row(VteTerminal *vte) {
             ^~~~~~~~~~
termite.cc:789:13: warning: ‘long int middle_row(VteTerminal*)’ defined but not used [-Wunused-function]
 static long middle_row(VteTerminal *vte) {
             ^~~~~~~~~~
termite.cc:784:13: warning: ‘long int top_row(VteTerminal*)’ defined but not used [-Wunused-function]
 static long top_row(VteTerminal *vte) {
             ^~~~~~~
termite.cc:356:21: warning: ‘const char* binding_get_name(keybinding_cmd)’ defined but not used [-Wunused-function]
 static const char * binding_get_name(keybinding_cmd cmd) {
                     ^~~~~~~~~~~~~~~~
termite.cc: In function ‘void move_to_eol(VteTerminal*, select_info*)’:
termite.cc:2127:1: warning: assuming signed overflow does not occur when changing X +- C1 cmp C2 to X cmp C2 -+ C1 [-Wstrict-overflow]
 }
```

2018-07-11 18:35 UTC, jelly commented
These are other compiler warnings caused by this change:
```
                                                                                                                       ^~~~
termite.cc: At global scope:
termite.cc:92:11: warning: no previous declaration for ‘guint vi_mode::parse_mode(const char*)’ [-Wmissing-declarations]
     guint parse_mode ( const char *q )
           ^~~~~~~~~~
termite.cc:129:12: warning: no previous declaration for ‘gchar* vi_mode::to_string(guint)’ [-Wmissing-declarations]
     gchar *to_string ( const guint mode )
            ^~~~~~~~~
termite.cc: In function ‘const char* binding_get_name(keybinding_cmd)’:
termite.cc:359:23: warning: comparison of integer expressions of different signedness: ‘int’ and ‘long unsigned int’ [-Wsign-compare]
     for (int i = 0; i < num_bindings; ++i) {
                     ~~^~~~~~~~~~~~~~
```

2018-09-09 13:51 UTC, ThrosturX commented
Hey @jelly , hope you don't mind the mad delays during the summer ;) I don't have access to my workstation right now but I pushed some changes that should address these issues. I'd love to see if there is anything left to complain about, since I'm not in the position to build the project properly right now.

2019-04-14 20:23 UTC, ThrosturX commented
Made some updates. README Updated mostly. Seems like all the compiler errors are there without my patch, so ignoring the ones that are left.

2019-05-01 01:47 UTC, dsifford commented
@jelly What needs to happen for this PR to merge?

2019-05-10 10:27 UTC, ThrosturX commented
Resolved the merge conflict caused by PR #660, this patch already solved that issue so the code was just deleted.

2019-05-10 16:27 UTC, jelly requested changes

2019-05-10 16:27 UTC, jelly commented on termite.cc
> +*/
Something is still wrong here :)

2019-05-10 16:27 UTC, jelly commented on termite.cc
> +=======
also small issue here :)

2019-05-10 16:40 UTC, ThrosturX commented on termite.cc
> +*/
Sorry about that, absolutely my bad.

2019-05-10 16:41 UTC, ThrosturX commented on termite.cc
> +=======
SO sorry about this one, should absolutely have caught that myself, my bad indeed!

2019-07-20 14:25 UTC, laktak commented
Would this PR allow us to disable the default keybindings like requested in #507?

Why are the defaults set in code instead of a default config file?

2020-01-23 01:34 UTC, codeclem commented
Is this PR missing anything to be merge ready?

2020-01-24 09:35 UTC, ThrosturX commented
Do I understand correctly that the requested change is just an update to README.rst?

2021-05-07 11:50 UTC, thestinger commented
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.

2021-05-07 11:50 UTC, closed without merging